name: Check projects quality
run-name: check projects quality
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: []
jobs:
  check-cdata-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install cdata dependencies
        run: pnpm install

      - name: Run cdata lint
        run: pnpm run lint

      - name: Run cdata typecheck
        run: pnpm run typecheck
  check-components-quality:
    defaults:
      run:
        working-directory: ./datagouv-components
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install datagouv-components dependencies
        run: pnpm install

      - name: Run datagouv-components typecheck
        run: pnpm run typecheck

      - name: Run datagouv-components linter
        run: pnpm run lint
